import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import WebSocket from 'ws';
import {engine} from '../world/core.js';
const base=process.env.WORLD_URL??'http://127.0.0.1:8787',core=engine(new WebAssembly.Instance(new WebAssembly.Module(readFileSync('world/engine.wasm')),{}));
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function client(cookie){if(!cookie){const r=await fetch(base+'/api/session',{method:'POST',headers:{Origin:base}});assert.equal(r.status,200);cookie=r.headers.get('set-cookie').split(';')[0];}const ws=new WebSocket(base.replace('http','ws')+'/api/connect',{headers:{Cookie:cookie,Origin:base}}),messages=[],waiters=[];const c={ws,cookie,messages,patches:new Map(),people:new Map(),wait(pred){const found=messages.findIndex(pred);if(found>=0)return Promise.resolve(messages.splice(found,1)[0]);return new Promise((resolve,reject)=>{const w={pred,resolve:m=>{clearTimeout(w.timeout);resolve(m);}};w.timeout=setTimeout(()=>reject(Error('Timed out waiting for server')),5000);waiters.push(w);});}};
ws.on('message',data=>{const m=JSON.parse(data);if(m.player&&['ack','welcome','snapshot'].includes(m.type))c.player=m.player;if(m.type==='welcome'||m.type==='snapshot'){for(const p of m.patches)c.patches.set(`${p.x},${p.y}`,p.tile);c.people.clear();for(const p of m.players)c.people.set(p.id,p);}if(m.type==='join'||m.type==='event')c.people.set(m.player.id,m.player);if(m.type==='leave')c.people.delete(m.id);if(m.patch)c.patches.set(`${m.patch.x},${m.patch.y}`,m.patch.tile);const i=waiters.findIndex(w=>w.pred(m));if(i>=0)waiters.splice(i,1)[0].resolve(m);else messages.push(m);});ws.on('error',e=>{for(const w of waiters)w.resolve({type:'socket-error',error:e.message});});const welcome=await c.wait(m=>m.type==='welcome');assert.equal(welcome.seed,1709123);return c;}
async function send(c,kind,dx,dy,structure=0){await pause(145);c.ws.send(JSON.stringify({type:'action',seq:c.player.seq+1,kind,dx,dy,structure}));const ack=await c.wait(m=>m.type==='ack');if(ack.code===0)await c.wait(m=>m.type==='event'&&m.player.id===c.player.id&&m.action.seq===c.player.seq);return ack;}
function tile(c,x,y){return c.patches.get(`${x},${y}`)??core.tile(x,y);}
async function walk(c,x,y){for(let step=0;step<100&&!(c.player.x===x&&c.player.y===y);step++){const q=[[c.player.x,c.player.y,[]]],seen=new Set();let path;while(q.length){const [a,b,p]=q.shift();if(a===x&&b===y){path=p;break;}for(const [dx,dy]of [[1,0],[0,1],[-1,0],[0,-1]]){const xx=a+dx,yy=b+dy,k=`${xx},${yy}`;if(seen.has(k)||Math.abs(xx)>13||Math.abs(yy)>13||!core.walkable(tile(c,xx,yy))||[...c.people.values()].some(o=>o.id!==c.player.id&&o.x===xx&&o.y===yy))continue;seen.add(k);q.push([xx,yy,[...p,[dx,dy]]]);}}assert.ok(path?.length,'reachable test site');const [dx,dy]=path[0];assert.equal((await send(c,1,dx,dy)).code,0);}assert.deepEqual([c.player.x,c.player.y],[x,y]);}
if(process.argv.includes('--resume')){const expected=JSON.parse(readFileSync('build/persistence-test.json')),c=await client(expected.cookie);assert.deepEqual(c.player,expected.player);assert.equal(tile(c,expected.x,expected.y),expected.tile);c.ws.close();console.log('PASS: player inventory, position, sequence, and tile edit survived server restart');process.exit(0);}
assert.equal((await fetch(base+'/api/session',{method:'POST',headers:{Origin:'https://invalid.example'}})).status,403);
const a=await client(),b=await client();assert.notEqual(a.player.id,b.player.id);await a.wait(m=>m.type==='join'&&m.player.id===b.player.id);
const before={...a.player};a.ws.send(JSON.stringify({type:'action',seq:a.player.seq+1,kind:1,dx:100,dy:0}));assert.equal((await a.wait(m=>m.type==='ack')).code,1);assert.deepEqual(a.player,before);
a.ws.send('null');assert.equal((await a.wait(m=>m.type==='ack')).code,1);
let site;for(let y=-10;y<=10&&!site;y++)for(let x=-10;x<=10&&!site;x++){const t=tile(a,x,y),o=t>>>16&255;if(o>=1&&o<=4&&core.walkable(tile(a,x-1,y))&&core.walkable(tile(a,x+1,y)))site={x,y,t};}assert.ok(site);
await walk(a,site.x-1,site.y);await walk(b,site.x+1,site.y);
const initial=a.player.wood+b.player.wood;while((tile(a,site.x,site.y)>>>24)>1)assert.equal((await send(a,2,1,0)).code,0);
await pause(150);a.messages.length=0;b.messages.length=0;for(const [c,dx]of [[a,1],[b,-1]])c.ws.send(JSON.stringify({type:'action',seq:c.player.seq+1,kind:2,dx,dy:0}));const outcomes=await Promise.all([a.wait(m=>m.type==='ack'),b.wait(m=>m.type==='ack')]);assert.deepEqual(outcomes.map(m=>m.code).sort(),[0,4]);assert.equal(a.player.wood+b.player.wood-initial,4);await pause(50);assert.equal(tile(a,site.x,site.y),tile(b,site.x,site.y));
const owner=a.player.wood>=2?a:b,dx=owner===a?1:-1;assert.equal((await send(owner,3,dx,0,16)).code,0);await pause(50);assert.equal(tile(a,site.x,site.y)>>>16&255,16);assert.equal(tile(a,site.x,site.y),tile(b,site.x,site.y));
const saved={...owner.player};owner.ws.send(JSON.stringify({type:'action',seq:saved.seq,kind:3,dx,dy:0,structure:16}));assert.equal((await owner.wait(m=>m.type==='ack')).code,9);assert.deepEqual(owner.player,saved);
writeFileSync('build/persistence-test.json',JSON.stringify({cookie:owner.cookie,player:saved,x:site.x,y:site.y,tile:tile(owner,site.x,site.y)}),{mode:0o600});
a.ws.close();b.ws.close();await pause(200);const again=await client(owner.cookie);assert.deepEqual(again.player,saved);assert.equal(tile(again,site.x,site.y)>>>16&255,16);again.ws.close();console.log('PASS: two players share one world; origin/schema/sequence validation; contested harvest grants once; building broadcasts; reconnect restores state');
