import {loadEngine,newPlayer,BIOMES,OBJECTS,ERRORS,WORLD_SEED,ENGINE_VERSION,LIMIT} from './core.js';
import {createPlayer,renderPlayer,animationFrames} from '../src/generator.js';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false});
const chunks=new Map(),patches=new Map(),people=new Map(),sprites=new Map(),keys=new Set();
let core,player=newPlayer('local'),socket,pending=false,online=false,mode=0,zoom=2,hover=null,facing={dx:0,dy:1},lastAction=0,animation=0,view={x:0,y:0},ready=false;
const key=(x,y)=>`${x},${y}`,tileSize=16,colors={1:['#586e3d','#627747','#526839'],2:['#c4b37d','#ccbb85','#baac77'],3:['#2b6870','#2e6e76','#29616d'],4:['#51494b','#584d50','#484248'],5:['#d36132','#e77c37','#ad422b'],6:['#867452','#907d59','#7e6b4d']};
function notice(t){$('#message').textContent=t;}
function getTile(x,y){const edit=patches.get(key(x,y));if(edit!==undefined)return edit;if(x<-LIMIT||x>=LIMIT||y<-LIMIT||y>=LIMIT)return core.tile(x,y);const cx=Math.floor(x/32),cy=Math.floor(y/32),k=key(cx,cy);let chunk=chunks.get(k);if(!chunk){chunk=core.chunk(cx,cy);chunks.set(k,chunk);if(chunks.size>128)chunks.delete(chunks.keys().next().value);}return chunk[(y-cy*32)*32+x-cx*32];}
function updateHUD(){if(!core)return;$('#coords').textContent=`${player.x} E · ${-player.y} N`;$('#biome').textContent=BIOMES[getTile(player.x,player.y)&255];for(const r of ['wood','stone','ore','fiber'])$('#'+r).textContent=player[r];if(online)$('#connection').textContent=`Shared world · ${people.size} online`;}
function sprite(id){if(sprites.has(id))return sprites.get(id);const character=createPlayer(id,'nonbinary',{classId:'townsfolk',faction:'mossbound'});character.equipment='pickaxe';const convert=f=>{const c=document.createElement('canvas');c.width=f.width;c.height=f.height;c.getContext('2d').putImageData(new ImageData(f.pixels,f.width,f.height),0,0);return c;};const frames=Object.fromEntries(['front','back','left','right'].map(d=>[d,convert(renderPlayer(character,d))]));const result={frames,character,actions:null};sprites.set(id,result);if(sprites.size>64)sprites.delete(sprites.keys().next().value);return result;}
function actionFrames(s){return s.actions??=animationFrames(s.character,'pickaxe_swing').map(frame=>Object.fromEntries(Object.entries(frame).filter(([d])=>['front','back','left','right'].includes(d)).map(([d,f])=>{const c=document.createElement('canvas');c.width=f.width;c.height=f.height;c.getContext('2d').putImageData(new ImageData(f.pixels,f.width,f.height),0,0);return [d,c];})));}
function choose(n){mode=n;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.mode)===n)));notice(['Collect nearby trees, rocks, ore, and fiber.','Wood wall · costs 2 wood','Stone wall · costs 2 stone','Wood floor · costs 1 wood','Bridge over water · costs 3 wood','Remove a built tile · recover 1 material'][n]);}
function saveLocal(){try{localStorage.setItem('agent-town-world-preview-v1',JSON.stringify({player,patches:[...patches]}));}catch{notice('Preview storage is full. Progress will last for this visit.');}}
function act(kind,dx,dy,structure=0){if(!ready||pending||performance.now()-lastAction<135)return;if(!dx&&!dy)return;lastAction=performance.now();facing={dx,dy};const command={type:'action',seq:player.seq+1,kind,dx,dy,structure};if(kind===2)animation=performance.now()+800;if(online){pending=true;socket.send(JSON.stringify(command));return;}const x=player.x+dx,y=player.y+dy,target=getTile(x,y),result=core.apply(player,command,target);player={...result.player,seq:command.seq};if(!result.code&&result.tile!==target)patches.set(key(x,y),result.tile);if(result.code)notice(ERRORS[result.code]);else if(kind!==1)notice(kind===2?(result.tile>>>24?'Keep swinging…':'Collected. Your inventory has been updated.'):kind===3?'Built. A little more town in the wilderness.':'Removed. Recovered one material.');saveLocal();updateHUD();}
function interact(dx,dy){if(Math.abs(dx)>1||Math.abs(dy)>1){notice('Move closer. You can reach the eight tiles around you.');return;}act(mode===0?2:mode===5?4:3,dx,dy,mode>0&&mode<5?15+mode:0);}
function offline(){try{const saved=JSON.parse(localStorage.getItem('agent-town-world-preview-v1'));if(saved){player=saved.player;for(const [k,t]of saved.patches)patches.set(k,t);}}catch{}ready=true;$('#connection').textContent='Local preview · saved on this device';notice('Local preview. Collect wood east of the clearing; rock is west.');updateHUD();}
async function connect(){let response;try{response=await fetch('/api/session',{method:'POST'});}catch{offline();return;}if(response.status===404||response.status===405){offline();return;}if(!response.ok){notice('The shared world could not admit this player. Reload to retry.');$('#connection').textContent='Connection unavailable';return;}socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/connect`);socket.onmessage=event=>{const m=JSON.parse(event.data);if(m.type==='welcome'||m.type==='snapshot'){if(m.seed!==WORLD_SEED||m.engineVersion!==ENGINE_VERSION){socket.close();notice('World version changed. Reload to update.');return;}player=m.player;people.clear();for(const p of m.players)people.set(p.id,p);patches.clear();for(const p of m.patches)patches.set(key(p.x,p.y),p.tile);online=ready=true;pending=false;$('#connection-dot').className='online';if(m.type==='welcome')notice('Welcome to the shared world. Every harvest and building is saved.');}
if(m.type==='ack'){pending=false;player=m.player;if(m.code)notice(ERRORS[m.code]??(m.code===10?'A little slower…':'Position synchronized. Try again.'));else if(mode!==0)notice('World updated.');}
if(m.type==='event'){people.set(m.player.id,{...m.player,dir:m.action.dy<0?'back':m.action.dy>0?'front':m.action.dx<0?'left':'right'});if(m.patch&&Math.abs(Math.floor(m.patch.x/32)-Math.floor(player.x/32))<=2&&Math.abs(Math.floor(m.patch.y/32)-Math.floor(player.y/32))<=2)patches.set(key(m.patch.x,m.patch.y),m.patch.tile);if(m.player.id===player.id&&m.action.kind===2)notice(m.patch?.tile>>>24?'Keep swinging…':'Collected. Your inventory has been updated.');}
if(m.type==='join')people.set(m.player.id,m.player);if(m.type==='leave')people.delete(m.id);updateHUD();};socket.onclose=()=>{online=ready=false;pending=false;$('#connection-dot').className='';$('#connection').textContent='Disconnected · reload to reconnect';notice('Connection closed. Your shared progress is saved. Reload to reconnect; use one tab per player.');};socket.onerror=()=>notice('Could not connect. This player may already be open in another tab.');}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}
function object(o,x,y,h){rect(x+2,y+11,13,4,'#203b2e66');if(o<=4){rect(x+7,y+4,3,10,'#74533b');if(o===1){rect(x+3,y-6,10,6,'#294934');rect(x+1,y,14,6,'#35563a');rect(x-1,y+6,18,5,'#416341');rect(x+6,y-10,4,6,'#4d7248');}else if(o===3){rect(x+8,y-7,2,18,'#8a6944');rect(x-2,y-8,20,4,'#527447');rect(x+2,y-11,12,4,'#67844b');rect(x-3,y-5,7,3,'#47693b');rect(x+14,y-5,6,3,'#47693b');}else{const c=o===4?['#204b38','#2c6040','#47764b']:['#3c5734','#4b693c','#71864b'];rect(x+1,y-7,14,16,c[0]);rect(x-2,y-3,20,11,c[1]);rect(x+1,y-8,11,9,c[2]);rect(x+10,y+1,7,6,c[0]);rect(x+2,y-5,3,2,'#8a9954');}}
else if(o===5||o===6){rect(x+2,y+5,13,9,'#4b5552');rect(x+3,y+2,10,10,o===6?'#79776f':'#8b9183');rect(x+5,y+1,6,3,'#b0b09a');rect(x+2,y+10,12,3,'#5e6963');if(o===6){rect(x+4,y+5,3,3,'#b58867');rect(x+10,y+8,3,2,'#d6a674');}}else if(o===7){rect(x+4,y+9,2,5,'#a6b277');rect(x+8,y+6,2,8,'#bfd091');rect(x+11,y+8,2,6,'#90a468');}
else if(o===16){rect(x,y-3,16,18,'#69503a');for(let i=1;i<16;i+=4)rect(x+i,y-2,2,16,'#a08454');rect(x,y-3,16,3,'#c09c64');rect(x,y+9,16,2,'#463e30');}else if(o===17){rect(x,y-3,16,18,'#626b64');rect(x,y-3,16,3,'#aab09b');for(let i=0;i<3;i++){rect(x,y+1+i*5,16,1,'#414e47');rect(x+(i%2?4:10),y-2+i*5,1,4,'#414e47');}}}
function draw(now){requestAnimationFrame(draw);if(!core)return;const w=Math.min(1280,Math.ceil(canvas.clientWidth/zoom)),h=Math.min(960,Math.ceil(canvas.clientHeight/zoom));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.imageSmoothingEnabled=false;view={x:player.x*16+8-w/2,y:player.y*16+8-h/2};const x0=Math.floor(view.x/16)-1,y0=Math.floor(view.y/16)-2,x1=Math.ceil((view.x+w)/16)+1,y1=Math.ceil((view.y+h)/16)+3;const objects=[];
for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const t=getTile(x,y),g=t>>>8&255,o=t>>>16&255,b=t&255,hsh=core.variant(x,y),sx=x*16-view.x,sy=y*16-view.y,palette=colors[g]??colors[1];rect(sx,sy,16,16,palette[hsh%3]);if(g===3||g===5){const phase=Math.floor(now/850);rect(sx+((hsh+phase)%9),sy+4,5,1,g===3?'#50878a':'#ffb452');rect(sx+3,sy+11,3,1,g===3?'#377a7e':'#f58938');}else{rect(sx+(hsh%12),sy+(hsh>>>4)%14,2,1,g===2?'#e0cc98':b===4?'#796365':'#799153');if(hsh%5===0&&g===1)rect(sx+8,sy+8,1,2,b===5?'#a9b751':'#a5a663');}if(o===18||o===19){rect(sx,sy,16,16,o===19?'#72583b':'#927647');for(let i=0;i<16;i+=4){rect(sx,sy+i,16,1,'#4a4430');rect(sx+1,sy+i+1,14,1,'#b19962');}if(o===19){rect(sx,sy,2,16,'#cab57b');rect(sx+14,sy,2,16,'#cab57b');}}else if(o)objects.push({x,y,o,hsh});}
const direction=facing.dy<0?'back':facing.dy>0?'front':facing.dx<0?'left':'right';const actors=[...people.values()].filter(p=>p.id!==player.id&&Math.abs(p.x-player.x)<60&&Math.abs(p.y-player.y)<45).map(p=>({...p,actor:true}));actors.push({...player,actor:true,dir:direction,self:true});for(const item of [...objects,...actors].sort((a,b)=>a.y-b.y||Number(Boolean(a.actor))-Number(Boolean(b.actor)))){const sx=item.x*16-view.x,sy=item.y*16-view.y;if(!item.actor){object(item.o,sx,sy,item.hsh);continue;}const s=sprite(item.id),dir=item.dir??'front';rect(sx+2,sy+11,12,4,'#16302388');if(item.self&&animation>now){const frame=actionFrames(s)[Math.min(7,Math.floor((800-animation+now)/100))][dir];ctx.drawImage(frame,Math.round(sx-8),Math.round(sy-13),32,32);}else ctx.drawImage(s.frames[dir],Math.round(sx-4),Math.round(sy-10),24,24);if(item.self){rect(sx+5,sy-13,6,1,'#ead49b');rect(sx+7,sy-12,2,2,'#ead49b');}}
if(hover){const sx=hover.x*16-view.x,sy=hover.y*16-view.y;ctx.strokeStyle=Math.max(Math.abs(hover.x-player.x),Math.abs(hover.y-player.y))<=1?'#f1d99a':'#dbd9b577';ctx.lineWidth=1;ctx.strokeRect(Math.round(sx)+.5,Math.round(sy)+.5,15,15);}
if(ready&&!pending){const up=keys.has('w')||keys.has('ArrowUp'),down=keys.has('s')||keys.has('ArrowDown'),left=keys.has('a')||keys.has('ArrowLeft'),right=keys.has('d')||keys.has('ArrowRight');if(up||down||left||right)act(1,left?-1:right?1:0,left||right?0:up?-1:1);}}
function atlas(){const c=$('#map'),g=c.getContext('2d'),img=g.createImageData(256,256),pal={1:[83,111,61],2:[202,181,122],3:[43,99,112],4:[118,75,66],5:[39,81,51]};for(let y=0;y<256;y++)for(let x=0;x<256;x++){const rgb=pal[core.tile((x-128)*16,(y-128)*16)&255];img.data.set([...rgb,255],(y*256+x)*4);}g.putImageData(img,0,0);g.fillStyle='#fff0bc';g.fillRect(126,127,5,1);g.fillRect(128,125,1,5);}
function toggleAtlas(){$('#atlas').hidden=!$('#atlas').hidden;}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.mode)));$('#atlas-toggle').onclick=toggleAtlas;$('#atlas-close').onclick=toggleAtlas;
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();const k=e.key.length===1?e.key.toLowerCase():e.key;keys.add(k);if(e.repeat)return;if(['w','ArrowUp'].includes(k))act(1,0,-1);if(['s','ArrowDown'].includes(k))act(1,0,1);if(['a','ArrowLeft'].includes(k))act(1,-1,0);if(['d','ArrowRight'].includes(k))act(1,1,0);if(/^[1-6]$/.test(k))choose(Number(k)-1);if(k==='e')interact(facing.dx,facing.dy);if(k==='m')toggleAtlas();if(k==='+'||k==='=')zoom=Math.min(4,zoom+1);if(k==='-')zoom=Math.max(1,zoom-1);});window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>keys.clear());
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();hover={x:Math.floor((view.x+(e.clientX-r.left)*canvas.width/r.width)/16),y:Math.floor((view.y+(e.clientY-r.top)*canvas.height/r.height)/16)};});canvas.addEventListener('pointerleave',()=>hover=null);canvas.addEventListener('pointerdown',e=>{canvas.focus();const r=canvas.getBoundingClientRect(),x=Math.floor((view.x+(e.clientX-r.left)*canvas.width/r.width)/16),y=Math.floor((view.y+(e.clientY-r.top)*canvas.height/r.height)/16);interact(x-player.x,y-player.y);});
try{core=await loadEngine();atlas();requestAnimationFrame(draw);await connect();}catch(e){notice(`Could not open the world: ${e.message}`);$('#connection').textContent='World unavailable';}
